### ISSUE TITLE
Płynne przesuwanie strony przyciskiem "INNE OPCJE"

### ISSUE THREAD

**Issue by doteq** [wulkanowy/wulkanowy.github.io#5]
Podczas naciśnięcia przycisku "INNE OPCJE" strona przesuwa się płynnie tylko, gdy url to https://wulkanowy.github.io/#download. Jeżeli adres to https://wulkanowy.github.io/, strona przeskakuje.

**Comment by dominik-korsa** [comment]
Przycisk już nie zmienia url na `#download`, tylko przesuwa widok, więc nie ma już tego problemu.
